### ISSUE TITLE
Adding Papers Without DOIs To Local Citation Network

### ISSUE THREAD

**Issue by dukebw** [LocalCitationNetwork/LocalCitationNetwork.github.io#1]
Hello! Thank you for the awesome project -- I think it will change the way I do literature reviews.

I am interested in adding the ability to reference papers that do not have a DOI, which appears common for conferences in machine learning (e.g., ICLR and NeurIPS). I was wondering whether you have any recommendations about the best way to approach this.

Thank you in advance!

**Comment by timwoelfle** [comment]
Hey Brendan, thanks for your feedback! Can the conference papers you're talking about be found on Microsoft Academic? If so it might be feasible to implement the possibility to add them via their Microsoft Academic ID.

**Comment by dukebw** [comment]
Hi Tim, I did try using the Microsoft Academic ID, which worked great for some papers, however it seems that Microsoft Academic is still missing metadata for many machine learning papers, for example, "Spectral Normalization for Generative Adversarial Networks" https://academic.microsoft.com/paper/2963836885 is missing references.

To my knowledge, the only paper tracking API for machine learning papers that works well is Semantic Scholar, which is used by papergraph https://github.com/dennybritz/papergraph. However your organization of the citation graph is much better for literature review (papergraph uses overall citation count for node size, for example). It would be awesome to merge the ideas from these two projects, and I'd like to work on that once I have time, but I realize it may be a decent amount of work.

**Comment by timwoelfle** [comment]
I've implemented it now and I find it quite useful for conference papers and arXiv, thanks for the idea :) Try e.g. https://timwoelfle.github.io/Local-Citation-Network/?API=Microsoft%20Academic&source=2626778328
