### ISSUE TITLE
Make use of the OpenCitations API?

### ISSUE THREAD

**Issue by no-identd** [LocalCitationNetwork/LocalCitationNetwork.github.io#2]
https://opencitations.net/querying

**Comment by timwoelfle** [comment]
Good idea, I've implemented it! For now the OpenCitations API often returns Internal Server Error 500 unfortunately though, it seems it can only handle rather small ipnut sets (around 30 DOIs mostly seem to work). It's a start though and definitely super interesting as it allows to suggest new articles that reference the input articles ("Outgoing suggestions")!

**Comment by no-identd** [comment]
@timwoelfle https://github.com/CitationGecko/gecko-react also uses the Opencitations API (among other APIs) and iirc implemented a workaround for that issue (I might have it mixed up with a different project, tho.). It's MIT licensed so (but I am not a lawyer, this isn't legal advice, etc.) taking a look at their source code should provide some answers & doesn't risking license pollution. :)
