### ISSUE TITLE
Web Layout Broken

### ISSUE THREAD

**Issue by chaichontat** [LocalCitationNetwork/LocalCitationNetwork.github.io#3]
Hi! I have enjoyed your tool for quite a while. However, the web interface does not seem to look correct today. This happens both on Firefox and Safari.

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/34997334/150156727-833cb700-e15c-47f1-8921-093bbe786abf.png">

**Comment by timwoelfle** [comment]
Thanks for letting me know, I wouldn't have notices! It was a simple mistake in my last commit and is fixed now.
